apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          # Replace 106373982378 and us-east-1 accordingly
          image: 106373982378.dkr.ecr.us-east-1.amazonaws.com/auth-service:latest
          ports:
            - containerPort: 80
          env:
            # Replace the following environment values with your actual DB credentials
            - name: DB_HOST
              value: mini-db.cluster-cml6q4a2qh3g.us-east-1.rds.amazonaws.com      # Replace accordingly
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: mini-db                          # Replace accordingly
            - name: DB_USER
              value: postgres                       # Replace accordingly
            - name: DB_PASSWORD
              value: Kanthavel8733                      # Replace accordingly

